<?php


namespace SimpleMagento\Database\Model\ResourceModel\AffiliateMember;


use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;
use SimpleMagento\Database\Model\AffiliateMember;
use SimpleMagento\Database\Model\ResourceModel\AffiliateMember as AffiliateMemberResource;

class Collection extends AbstractCollection
{
    protected function _construct()
    {
//        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init(AffiliateMember::class, AffiliateMemberResource::class);
    }
}