<?php declare(strict_types=1);
/** @var \Magento\Framework\View\Element\Template $block */
?>


<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app":{
                "components":{
                    "startSimple":{
                        "component":"SimpleMagento_CollapseWidget/js/plain-view-model",
                        "base-url":"<?= $block->escapeJs($block->getBaseUrl()) ?>   "
                    }
                }
            }
        }
    }
</script>
<div data-bind="scope: 'startSimple'">
<!--    <h2 data-bind="text: title"></h2>-->
    <pre data-bind="text: output"></pre>
</div>