<div id="my-collapsible" data-mage-init='{"SimpleMagento_CollapseWidget/js/dynamic-collapsible": {"ajaxContent": true} }'> <!-- {"active": true, "saveState": true} -->
    <div data-role="title">
        <h2> how collaspisble widget <button data-role="trugger">Go</button> </h2>
    </div>
    <div id="example" data-role="content"></div>
    <a href="<?= $block->getViewFileUrl('SimpleMagento_CollapseWidget/example-content.html') ?>" data-ajax="true"></a>
</div>

<!--<form data-mage-init='{"validation": {}}'>-->
<!--    <div class="control">-->
<!--        <input type="text" name="email" id="email" class="input-text" placeholder="--><?//= __('Your email') ?><!--" data-validate="{required:true, 'validate-email':true}" />-->
<!--    </div>-->
<!--    <button type="submit" class="action-primary">--><?//= _('Submit') ?><!--</button>-->
<!--</form>-->